language: python

install:
  - pip install tox coveralls

script: tox

notifications:
  email: false

after_success:
  - coveralls

cache: pip

matrix:
    include:
        - python: 3.4
          env: TOXENV=py34
