FROM ubuntu:17.10

ARG DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV SHELL=/bin/bash

# install apt-fast
RUN apt-get update && \
    apt-get install -y -f software-properties-common python-software-properties && \
    add-apt-repository ppa:apt-fast/stable && \
    apt-get update && \
    apt-get -y install apt-fast

# install sys deps
RUN apt-fast install -y python3 python3-dev python3-pip python3-venv

# install python deps
RUN pip3 install --user --upgrade pip setuptools pipenv
ENV PATH=/root/.local/bin:$PATH

# install app deps
RUN mkdir -p /app
WORKDIR /app
ADD Pipfile Pipfile.lock /app/
RUN rm -f Pipfile.lock
RUN pipenv install && pipenv install --dev

VOLUME ["/app"]
